# Generated by Django 5.2.4 on 2025-07-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_assignment_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assignment",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="assignments/"),
        ),
    ]
