# Generated by Django 5.2.4 on 2025-07-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_student_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="submission_file",
            field=models.FileField(blank=True, null=True, upload_to="submissions/"),
        ),
        migrations.AddField(
            model_name="grade",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
