# Generated by Django 5.2.4 on 2025-07-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_grade_submission_file_grade_submitted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="submission_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
