# Generated by Django 5.2.4 on 2025-07-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0008_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="student_photos/default.png",
                null=True,
                upload_to="student_photos/",
            ),
        ),
    ]
